FROM node:lts AS installer

ENV NODE_ENV=production

WORKDIR /app

ADD package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc /app/
ADD packages/api/package.json /app/packages/api/
RUN corepack enable && cd packages/api && pnpm install --prod --no-optional
ADD . /app

FROM oven/bun
ENV NODE_ENV=production
ENV PORT=3000


COPY --from=installer /app /app

CMD [ "bun", "run", "/app/packages/api/src/index.ts" ]
EXPOSE 3000
